# Generated by Django 2.1.1 on 2018-09-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180916_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='BEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best', models.CharField(max_length=200)),
            ],
        ),
    ]
