# Generated by Django 2.1.1 on 2018-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_best'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='posquote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
